### ISSUE TITLE
% based regen broken

### ISSUE THREAD

**Issue by Kruseified** [Wertik/BlockRegen#41] opened 2024-10-03 01:29 UTC
when setting regeneration blocks in a % based format (listed below)

COAL_ORE:35;COPPER_ORE:35;IRON_ORE

It will only generate the iron ore and no other, it will replace the other listed ores over whenever they are mined. Almost as if it has a 100% replace rate.

Please fix this asap, currently running on a 1.20.6 instance.

**Comment by Wertik** [comment] 2024-10-04 19:18
Hey, for a faster response time it would've been better to use Discord, as I don't have notifications here enabled. I'll look into this.

**Comment by Wertik** [comment] 2024-10-04 19:20
Since I don't know which version of the plugin you're using, i'll verify on the latest version provided here on GitHub. If the issue is there, i'll get to a fix, otherwise, please update.

**Comment by Wertik** [comment] 2024-10-04 19:39
Issue found, working on a fix.

**Comment by Wertik** [comment] 2024-10-04 21:16
Fixed in [3.11.3](https://github.com/Wertik/BlockRegen/releases/tag/3.11.3)

**Closed as completed by Wertik** 2024-10-04 21:16 UTC

**Comment by Kruseified** [comment] 2024-10-05 04:23
Thank you sir!
