### ISSUE TITLE
onDisable dont regen blocks

### ISSUE THREAD

**Issue by exzolink** [Wertik/BlockRegen#27] opened 2022-07-13 00:10 UTC
onDisable dont regen blocks due to registering bukkit tasks while disabling

**Comment by Wertik** [comment] 2022-07-15 23:01
Please provide any relevant information starting with the server version, plugin version, full stracktrace of the error or a way to reproduce the issue reliably.

**Comment by exzolink** [comment] 2022-07-19 11:13
You cant run tasks while disabling server. Check your revertAll method

**Comment by exzolink** [comment] 2023-04-15 22:06
@Wertik 
https://pastebin.com/7V0fLexR

**Comment by ExceptedPrism3** [comment] 2023-06-16 11:33
The same issue over here, it doesn't regen onDisable due to a runnable defect.

**Comment by exzolink** [comment] 2023-08-03 00:36
@Wertik hello?

**Comment by Wertik** [comment] 2024-09-28 22:25
This should be fixed in 3.11.2. Sorry for the late response.

**Closed as completed by Wertik** 2024-09-28 22:25 UTC
